"""Add invite option

Revision ID: 92461fd2c26b
Revises: ed4ae9a9a403
Create Date: 2024-08-01 10:55:33.752630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92461fd2c26b'
down_revision: Union[str, None] = 'ed4ae9a9a403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('invited_by_user_id', sa.String(length=36), nullable=True))
    op.add_column('family_members', sa.Column('accepted', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'family_members', 'users', ['invited_by_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'family_members', type_='foreignkey')
    op.drop_column('family_members', 'accepted')
    op.drop_column('family_members', 'invited_by_user_id')
    # ### end Alembic commands ###
