"""Add family owner column

Revision ID: a86f8c5d9f16
Revises: a6432b28721f
Create Date: 2024-07-19 10:59:42.342761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86f8c5d9f16'
down_revision: Union[str, None] = 'a6432b28721f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'families', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.drop_column('families', 'owner_id')
    # ### end Alembic commands ###
